### ISSUE TITLE
Is it possible to compile to  apple M1 ?

### ISSUE THREAD

**Issue by RustamKarimov3** [joseluisq/rust-linux-darwin-builder#10]

**Comment by RustamKarimov3** [comment]
I ve already tried in different ways. I changed CC and CXX params but not sure if I did that correctly. Did not found full example. Could you help me with this challenge?

**Comment by joseluisq** [comment]
Have a look a this one https://github.com/joseluisq/rust-linux-darwin-builder/issues/7

**Comment by RustamKarimov3** [comment]
@joseluisq Thanks a lot for everything!

**Comment by joseluisq** [comment]
Released on [v1.65.0](https://github.com/joseluisq/rust-linux-darwin-builder/releases/tag/v1.65.0)
