### ISSUE TITLE
Native linux/arm64 image?

### ISSUE THREAD

**Issue by markmandel** [joseluisq/rust-linux-darwin-builder#12]
Working on a Debian arm64 machine, and want to be able to cross compile to macOS.

I'm currently running this image under linux/amd64 emulation (Qemu) to work on my machine, but it's _sloooow_ 😥, and ultimately fails for reasons I've yet to determine.

Having a native linux/arm64 image would make things a lot faster, and I'm guessing less error prone! So figured I would ask to see if it was possible.

**Comment by markmandel** [comment]
Gist of the compilation failure, if you are interested:
https://gist.github.com/markmandel/14cc0d991d339a5d5f040f85a9f34297

Works perfectly on a linux/arm64 machine (which is still pretty awesome).

**Comment by markmandel** [comment]
I took a stab at attempting to make an image that would compile on arm64 and amd64, but ran into some issues I couldn't quite place on compiling OpenSSL. I haven't pushed this up anywhere, but happy to share if you think it would be useful.

**Comment by joseluisq** [comment]
> Having a native linux/arm64 image would make things a lot faster, and I'm guessing less error prone! So figured I would ask to see if it was possible.

Definitely, I am open to receiving help on that since I don't have an ARM64 of any kind at hand.
Please feel free to share your thoughts or even send a PR if you want.

**Comment by markmandel** [comment]
Sweet! I think I worked out my previous issue, and have it working - just testing the building of the multi-arch image now.

But I built the image on my arm image and made a macos binary with a [project I work on](https://github.com/googleforgames/quilkin), and it seems to have worked!

Will likely file a PR today.

**Comment by joseluisq** [comment]
That sounds great! Please let me know if you need me to review it. Also more than happy to promote a separate image tag on DockerHub if needed.

**Comment by markmandel** [comment]
Awesome - absolutely will get you to review. I've update the `Dockerfile` to make some changes depending on which arch it finds itself in, and then also updated the Makefile to cross build an image -- but I'm not sure how to integrate it all into your github workflow stuff, but I figured it was a good start and we can expand it from there.

**Comment by markmandel** [comment]
I love that 2 days or work results in ~30 lines of code 😃

Would love your review!

**Comment by joseluisq** [comment]
Released on [v1.65.0](https://github.com/joseluisq/rust-linux-darwin-builder/releases/tag/v1.65.0)

**Comment by markmandel** [comment]
OH LOOK AT THAT 🥳

**Comment by joseluisq** [comment]
It would be great to give the release a try, especially the _arm64_ :sweat_smile:

**Comment by markmandel** [comment]
https://github.com/googleforgames/quilkin/issues/642 has been written! Will take it for a spin soon.

**Comment by joseluisq** [comment]
And [this is the ritual](https://cirrus-ci.com/build/4802511769436160) about the release if useful or just out of curiosity.
