### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by markmandel** [joseluisq/rust-linux-darwin-builder#4]
This is just an issue to say 🎆 thank you for this project 🎆 - I thought cross compilation from linux to macOS was going to be a nightmare, but this made it super easy.

![image](https://user-images.githubusercontent.com/298370/123489650-481cfe80-d5c7-11eb-9e2a-fc22d9d48a5c.png)

**Comment by joseluisq** [comment]
Don't worry just enjoy it. 😅
